name: Deploy Resume

on:
    push:
        branches: [main]
    pull_request:
      branches: [main]
    workflow_dispatch:
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        container:
          image: daluce/cv:latest
          options: --entrypoint /bin/sh
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}

        steps:
            - name: Checkout source
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Build resume
              run: make all

            - name: Test
              run: make test
            - name: Upload PDFs and images to S3
            # Only upload on pushes to main branch, not PRs
              if: github.event_name == 'push'
              run: make release
